version: "3.7"

services:
  mongo:
    image: mongo
    volumes: 
      - banks_mongo_data:/data/db
    ports:
      - 27017:27017
    container_name: banks_mongo
    networks:
      - redis_mongo_gunicorn

  redis:
    image: redis
    volumes:
      - banks_redis_data:/data
    ports:
      - 6379:6379
    container_name: banks_redis
    networks:
      - redis_mongo_gunicorn

volumes:
  banks_mongo_data:
    driver: local
  banks_redis_data:
    driver: local

networks:
  redis_mongo_gunicorn:
    driver: "bridge" 